name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install pre-commit pytest
      - name: Run pre-commit
        run: pre-commit run --show-diff-on-failure --color=always --all-files
      - name: Run tests
        run: pytest -v
